apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  creationTimestamp: '2024-03-27T16:16:55Z'
  finalizers:
    - dscinitialization.opendatahub.io/finalizer
  generation: 1
  labels:
    app.kubernetes.io/created-by: opendatahub-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dscinitialization
    app.kubernetes.io/part-of: opendatahub-operator
  name: default-dsci
spec:
  applicationsNamespace: opendatahub
  monitoring:
    managementState: Managed
    namespace: opendatahub
